# Generated by Django 5.0 on 2023-12-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=100)),
                ("contact", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("slider", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
                ("popular", models.BooleanField(default=False)),
                ("latest", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=500)),
                ("image", models.ImageField(upload_to="media")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
            ],
        ),
    ]
