# Generated by Django 5.0 on 2023-12-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_contactinfo_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=100)),
                ("subject", models.TextField(blank=True)),
                ("message", models.TextField(blank=True)),
            ],
        ),
    ]
